title: Jekyll AC Testing Template
email: liam@bigelow.io

plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-postcss-v2
  - jekyll-local-assign

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ./bad-dir
  - ../../ac-components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

_select_data:
  page_themes:
    - Dark
    - Light
    - Soft

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: posts
      path: _posts
    values:
      color: "#DADB0D"
  -
    scope:
      type: items
      path: _items
    values:
      image: "https://place-puppy.com/50x50"

collections:
  items:
    name: 'Items'
    _icon: 'nature_people'
    _singular_name: 'Item'
    output: false
  posts:
    name: 'Posts'
    _icon: 'nature_people'
    _singular_name: 'Post'
    output: true
    permalink: /post/:slug/